spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888
resilience4j:
  retry:
    instances:
      sample-api:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
  circuitbreaker:
    instances:
      sample-api:
        failureRateThreshold: 70
        minimumNumberOfCalls: 10
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"