spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:\Downloads\spring-local-config-repo
          default-label: master
server:
  port: 8888